---
abstract: 'Use a Catalyst application as an object'
author:
  - 'Daniel Ruoso C<daniel@ruoso.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Engine-Embeddable
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80004
  HTTP::Body: 0
  HTTP::Request: 0
  HTTP::Response: 0
  Moose: 0
  URI: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Engine-Embeddable/trunk/
version: 0.000003
